### ISSUE TITLE
Limits of validity of refractive index models

### ISSUE THREAD

**Issue by DaveOri** [maahn/pyPamtra2#1]
Currently any refractive index model just check for physical limits of absolute temperature and frequency, i.e. it checks if they are negative and raises a ValueError in that case.

Actually each model has certain temperature and frequency range of validity. In case requested temperature and/or frequency are out of these boundaries the model should respond accordingly raising ValueError or switching almost transparently to an appropriate model

**Comment by maahn** [comment]
Your refractivity module looks great! Regarding the limits, I would favor a ValueError for now. This is much easier to implement and we could still make it more sophisticated if required later.

**Comment by DaveOri** [comment]
Fixed at a certain point.
For sure, limits of validity are implemented after 
b78dafbdaaa9802755c3cef5ddb2875880c954e6
CLOSING
