### ISSUE TITLE
Measuring units

### ISSUE THREAD

**Issue by DaveOri** [maahn/pyPamtra2#2]
I am not sure if we already discuss it (quite sure I have discuss it in many different projects), but I think it really helps if we take a definitive decision about internal consistency of measuring units.

I am a strong supporter of SI and I think that is only way to go to ensure internal consistency, anything else makes the effort too large... Unfortunately I have already used GHz, millimeters, and grams/cm**3 here and there. Just wanted to raise the point

**Comment by maahn** [comment]
I totally agree. For the original Pamtra version we agreed to write new code in SI and for old code, we made sure that all function calls, parameters, etc. are in SI. The only exception, to my knowledge, is frequency in GHz. I think we should continue to do it like that, and maybe even use Hz for frequency (at least internally).

**Comment by DaveOri** [comment]
Since commit
b399bd40a09466ebe9cc380d79747d036e92d5d2
everything is in SI units (at least in the refractive index module)
closing
